# Generated by Django 5.2.6 on 2025-11-21 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('bibliografia', models.TextField()),
                ('paginaweb', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('editorialid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Editorial')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('sitioweb', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('pais', models.CharField(max_length=50, verbose_name='País de Origen')),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('eventoid', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogid', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fechapublicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('fecharegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferenciasgenero', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('libroid', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('aniopublicacion', models.IntegerField()),
                ('genero', models.CharField(choices=[('FIC', 'Ficción'), ('ROM', 'Romance'), ('TER', 'Terror'), ('CIE', 'Ciencia Ficción'), ('FAN', 'Fantasía'), ('HIS', 'Histórico'), ('BIO', 'Biografía'), ('INF', 'Infantil')], max_length=100)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('autorid', models.ForeignKey(db_column='autorid', on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.autor')),
                ('editorialid', models.ForeignKey(db_column='editorialid', on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.editorial')),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carritoid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fechaagregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.libro')),
            ],
            options={
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField(default=django.utils.timezone.now)),
                ('montototal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodopago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=50)),
                ('estadoventa', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=50)),
                ('descuentoaplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pagorecibido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clienteid', models.ForeignKey(db_column='clienteid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleventaid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.16, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libroid', models.ForeignKey(db_column='libroid', on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.libro')),
                ('ventaid', models.ForeignKey(db_column='ventaid', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Libreria.venta')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
