# Generated by Django 5.2.6 on 2025-11-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='preferenciasgenero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias_genero',
            field=models.TextField(blank=True),
        ),
    ]
