# Generated by Django 5.2.6 on 2025-12-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Libreria', '0002_remove_cliente_preferenciasgenero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-fechapublicacion'], 'verbose_name': 'Entrada de Blog', 'verbose_name_plural': 'Entradas de Blog'},
        ),
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('GENERAL', 'General'), ('RESENA', 'Reseñas de Libros'), ('AUTOR', 'Autores y Escritores'), ('EVENTO', 'Eventos Literarios'), ('TALLER', 'Talleres y Cursos'), ('NOTICIA', 'Noticias Editoriales'), ('RECOMENDACION', 'Recomendaciones'), ('ENTREVISTA', 'Entrevistas')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen breve para mostrar en listados'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='preferencias_genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
