# Generated by Django 5.2.6 on 2025-12-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Libreria', '0003_alter_blog_options_blog_categoria_blog_resumen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='capacidad',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('PRESENTACION', 'Presentación de Libro'), ('CLUB_LECTURA', 'Club de Lectura'), ('TALLER', 'Taller Literario'), ('FIRMA', 'Firma de Autores'), ('CONFERENCIA', 'Conferencia'), ('LANZAMIENTO', 'Lanzamiento'), ('INFANTIL', 'Evento Infantil')], default='PRESENTACION', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
