# Generated by Django 5.1 on 2025-12-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Libreria', '0004_alter_evento_options_evento_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='activo',
        ),
    ]
