# Generated by Django 5.2.6 on 2025-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Libreria', '0005_remove_evento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Evento activo'),
        ),
    ]
